---
# Run all tests
stages:
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

AWS Linux role from cookiecutter test:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - cookiecutter -f --no-input https://github.com/lean-delivery/ansible-development-kit
    - find . -type d -regex "./AWS\|./EPC\|./WINRM"
        -exec cp -R {} ansible-role-default_role/molecule/resources/provisioning/ \;
    - cp -R AWS ansible-role-default_role/molecule/resources/provisioning/
    - cd ansible-role-default_role
    - molecule test -s cloud-aws-direct
  tags:
    - aws

AWS Windows role from cookiecutter test:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - cookiecutter -f --no-input https://github.com/lean-delivery/ansible-development-kit
    - find . -type d -regex "./AWS\|./EPC\|./WINRM"
        -exec cp -R {} ansible-role-default_role/molecule/resources/provisioning/ \;
    - cp -R WINRM ansible-role-default_role/molecule/resources/provisioning/
    - cd ansible-role-default_role
    - molecule test -s cloud-aws-windows
  tags:
    - aws

EPC role from cookiecutter test:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - cookiecutter -f --no-input https://github.com/lean-delivery/ansible-development-kit
    - find . -type d -regex "./AWS\|./EPC\|./WINRM"
        -exec cp -R {} ansible-role-default_role/molecule/resources/provisioning/ \;
    - cp -R EPC ansible-role-default_role/molecule/resources/provisioning/
    - cd ansible-role-default_role
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
